name: Deploy VitePress site to Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  setup:
    uses: ./.github/workflows/setup.yml

  deploy:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.10.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Build tsup
        run: |
          cd third-parties/tsup
          pnpm install --no-frozen-lockfile
          pnpm build

      - name: Install dependencies
        run: |
          pnpm install --no-frozen-lockfile
          pnpm install --no-frozen-lockfile -w

      # not necessary
      # - name: Build packages
      #   run: pnpm build

      - name: Build docs
        run: pnpm docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
